spring:
  application:
    name: team3-plus-spring

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    defer-datasource-initialization: true

  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-millis: ${JWT_ACCESS_TOKEN_EXPIRATION_MILLIS}
